"""Documentation macros.

The worked-examples page is produced here rather than committed, so it cannot
show how the encoding *used* to look. A generated file that has to be
regenerated by hand is only a slower way of hand-maintaining it.

Registered through ``[project.plugins.macros]`` in ``zensical.toml``, which
zensical shims into a Markdown extension.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from awl import contracts, pipeline  # noqa: E402
from awl.astdoc import to_doc  # noqa: E402
from awl.compact import dumps, encode  # noqa: E402
from awl.elide import elide  # noqa: E402

#: Tiers first, in the order they build on each other, then the edge cases,
#: then the files nobody wrote for this project.
_ORDER = {"tier1_plain": 0, "tier2_dataclass": 1, "tier3_oold": 2, "edge": 3, "real": 4}


def _siblings(path: Path) -> dict[str, str]:
    """Return the modules a corpus file may import from.

    A parameter object lives in another file, so without these the constructor
    collapse cannot fire and the interesting half of the example is missing.
    """
    package = path.parent.name
    return {
        f"{package}.{other.stem}": other.read_text(encoding="utf-8")
        for other in sorted(path.parent.glob("*.py"))
        if other != path
    }


def _fence(text: str, language: str, indent: str = "") -> str:
    """Return a fenced block, indented for nesting inside a tab."""
    lines = [f"```{language}", *text.splitlines(), "```"]
    return "\n".join(indent + line if line else "" for line in lines)


def _views(path: Path) -> list[tuple[str, str]]:
    """Return each representation of one corpus file, as (tab title, JSON).

    Only the ``ast`` profile appears. It is the profile whose obligation is
    complete value provenance and the only one that regenerates its source.
    Further profiles get further tabs once each is defined by the class of
    question it must answer.
    """
    source = path.read_text(encoding="utf-8")
    module = f"{path.parent.name}.{path.stem}"
    return [
        (
            "AWL AST, collapsed",
            dumps(pipeline.to_compact(source, module=module, index=_siblings(path)), width=110),
        ),
        ("AWL AST, plain", dumps(encode(elide(to_doc(ast.parse(source)), profile="ast")), width=110)),
    ]


def _tabs(entries):
    """Return a tab set, one tab per (title, body, language).

    The source column gets one too, even with a single tab. A bare code block
    beside a tab set sits at a different height and reads as a different kind
    of thing, when the two are one artefact in two notations. It also leaves
    room for the source to gain a second tab without the layout shifting.
    """
    separator = "\n\n"
    return separator.join(
        '=== "' + title + '"\n\n' + _fence(body, language, "    ") for title, body, language in entries
    )


def _split_view(path: Path) -> str:
    """Return one file's source beside its representations."""
    return "\n".join([
        f"## `{path.parent.name}/{path.name}`",
        "",
        '<div class="grid" markdown>',
        "",
        '<div markdown="1">',
        "",
        _tabs([("Python", path.read_text(encoding="utf-8").rstrip(), "python")]),
        "",
        "</div>",
        "",
        '<div markdown="1">',
        "",
        _tabs([(title, rendered, "json") for title, rendered in _views(path)]),
        "",
        "</div>",
        "",
        "</div>",
        "",
    ])


def define_env(env) -> None:
    """Register the macros the documentation calls."""

    @env.macro
    def corpus_examples() -> str:
        """Return the split view for every file in the validation corpus."""
        files = sorted(
            contracts.corpus_files(),
            key=lambda path: (_ORDER.get(path.parent.name, 9), path.name),
        )
        return "\n".join(_split_view(path) for path in files)

    @env.macro
    def corpus_count() -> int:
        """Return how many files the corpus holds."""
        return len(contracts.corpus_files())
